-- =================================================================
-- MIGRATION: Crée les tables pour la configuration dynamique et le suivi des modèles ML.
-- Problème: Le SelfLearningEngine a besoin d'un endroit pour stocker et modifier la configuration de l'application.
-- Solution:
-- 1. Créer une table `app_config` pour les paires clé-valeur de configuration.
-- 2. Créer une table `ml_models` pour suivre les versions et performances des modèles.
-- 3. Créer une fonction RPC `apply_config_change` pour modifier la configuration de manière sécurisée.
-- =================================================================

-- ===========================================
-- 1. TABLE: app_config
-- Description: Stocke la configuration dynamique de l'application.
-- ===========================================

CREATE TABLE IF NOT EXISTS public.app_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    value JSONB,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.app_config IS 'Table de configuration clé-valeur pour les paramètres dynamiques de l''application.';

-- Activer RLS
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;

-- Politique: Les administrateurs peuvent tout faire, les autres peuvent lire.
CREATE POLICY "Admin full access" ON public.app_config FOR ALL USING (get_my_claim('role') = 'admin'::text);
CREATE POLICY "Users can read config" ON public.app_config FOR SELECT USING (true);


-- ===========================================
-- 2. TABLE: ml_models
-- Description: Suit les versions et performances des modèles de machine learning.
-- ===========================================

CREATE TABLE IF NOT EXISTS public.ml_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name TEXT NOT NULL UNIQUE,
    model_type TEXT,
    version TEXT,
    parameters JSONB,
    performance_metrics JSONB,
    is_active BOOLEAN DEFAULT TRUE,
    training_samples_count INTEGER,
    last_trained_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.ml_models IS 'Suivi des versions et performances des modèles ML internes.';

-- Activer RLS
ALTER TABLE public.ml_models ENABLE ROW LEVEL SECURITY;

-- Politique: Les administrateurs peuvent tout faire, les autres peuvent lire.
CREATE POLICY "Admin full access on ml_models" ON public.ml_models FOR ALL USING (get_my_claim('role') = 'admin'::text);
CREATE POLICY "Users can read ml_models" ON public.ml_models FOR SELECT USING (true);

-- Insérer une configuration par défaut pour le test
INSERT INTO public.app_config (key, value, description)
VALUES
  ('alert_threshold_temperature', '35'::jsonb, 'Seuil de température en °C pour déclencher une alerte de chaleur.'),
  ('feature_flag_weight_reminder', 'false'::jsonb, 'Active ou désactive les rappels pour la saisie du poids des lots.')
ON CONFLICT (key) DO NOTHING;